### ISSUE TITLE
Enable SketchKit layout DSL on UILayoutGuides

### ISSUE THREAD

**Issue by cs-nicholas-babo** [dogo/SketchKit#1]
### UILayoutGuides
UILayoutGuides are a great feature that UIKit has that allows developers to move on from using empty dummy UIViews as spacing or container views in order to achieve a specific spacing or alignment.

> There are a number of costs associated with adding dummy views to your view hierarchy. First, there is the cost of creating and maintaining the view itself. Second, the dummy view is a full member of the view hierarchy, which means that it adds overhead to every task the hierarchy performs. Worst of all, the invisible dummy view can intercept messages that are intended for other views, causing problems that are very difficult to find.

- Apple Developer Documentation

UILayoutGuide is quite useful and common, I believe it would be of great interest to be able to apply this DSL to these objects as well

`layoutGuide.layout.applyConstraint { $0.topAnchor(equalTo: view.topAnchor) }`

**Comment by dogo** [comment]
Please update to 1.2.0
